export const siteConfig = {
  name: 'תריסים חשמליים חכמים',
  businessName: 'תריסים חשמליים חכמים',
  phone: '050-8463015',
  whatsapp: '972508463015',
  email: 'info@smart-shutters.co.il',
  address: 'אזור המרכז, ישראל',
  url: 'https://www.smart-shutters.co.il',
  workingHours: 'א׳-ה׳ 07:00-20:00 | שישי 07:00-14:00 | שירות חירום 24/7',
  serviceAreas: [
    'תל אביב',
    'רמת גן',
    'גבעתיים',
    'הרצליה',
    'רעננה',
    'כפר סבא',
    'פתח תקווה',
    'ראשון לציון',
    'חולון',
    'בת ים',
    'נתניה',
    'אשדוד',
  ],
  socialLinks: {
    facebook: 'https://facebook.com/smart-shutters',
    instagram: 'https://instagram.com/smart-shutters',
    google: 'https://g.page/smart-shutters',
  },
} as const;
